export const AUTH_CHANGE_FIELD = 'AUTH_CHANGE_FIELD';
export const AUTH_SUBMIT_LOGIN = 'AUTH_SUBMIT_LOGIN';
export const AUTH_SUBMIT_SIGNUP = 'AUTH_SUBMIT_SIGNUP';
export const LOGIN_OK = 'LOGIN_OK';

export const CABINET_CHANGE_FIELD = 'CABINET_CHANGE_FIELD';
