// types auth
export const AUTH_CHANGE_FIELD = 'AUTH_CHANGE_FIELD';
export const AUTH_SUBMIT_LOGIN = 'AUTH_SUBMIT_LOGIN';
export const AUTH_SUBMIT_SIGNUP = 'AUTH_SUBMIT_SIGNUP';
export const LOGIN_OK = 'LOGIN_OK';
export const SIGNUP_OK = 'SIGNUP_OK';
export const LOGOUT = 'LOGOUT';
export const UPDATE_PROFIL = 'UPDATE_PROFIL';
export const UNSUB_NURSE = 'UNSUB_NURSE';
export const AUTO_LOGIN = 'AUTO_LOGIN';

//connexion_dashboard
export const INIT_DASHBOARD = 'INIT_DASHBOARD';

// types search
export const SEARCH_CHANGE_FIELD = 'SEARCH_CHANGE_FIELD';
export const SEARCH_SUBMIT = 'SEARCH_SUBMIT';

// types cabinets
export const CABINET_CHANGE_FIELD = 'CABINET_CHANGE_FIELD';
export const SEED_CABINETS = 'SEED_CABINETS';
export const SEED_DEFAULT_CABINET = "SEED_DEFAULT_CABINET";
export const CHANGE_CABINET = "CHANGE_CABINET";
export const CREATE_CABINET = "CREATE_CABINET";
export const CREATE_CABINET_SUCCEEDED = "CREATE_CABINET_SUCCEEDED";
export const UPDATE_CABINET = "UPDATE_CABINET";
export const CABINET_CHANGE_FIELD_UPDATE = "CABINET_CHANGE_FIELD_UPDATE";
export const SUB_CABINET = "SUB_CABINET";
export const UNSUB_CABINET = "UNSUB_CABINET";

//types patients
export const SEED_PATIENTS = "SEED_PATIENTS";
export const GET_PATIENTS = "GET_PATIENTS";
export const CREATE_PATIENT = "CREATE_PATIENT";
export const CREATE_PATIENT_SUCCEEDED = "CREATE_PATIENT_SUCCEEDED";
export const RESET_PATIENT_FIELD = "RESET_PATIENT_FIELD";
export const PATIENT_CHANGE_FIELD = "PATIENT_CHANGE_FIELD";
export const GET_PATIENT = "GET_PATIENT";
export const SEED_PATIENT = "SEED_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const UPDATE_PATIENT_SUCCEEDED = "UPDATE_PATIENT_SUCCEEDED";

//types logs
export const GET_LOGS = "GET_LOGS";
export const GET_LOGS_BY_DATE = "GET_LOGS_BY_DATE";
export const SEED_LOGS = "SEED_LOGS";
export const LOGBOOK_CHANGE_FIELD = "LOGBOOK_CHANGE_FIELD";
export const CREATE_LOG = "CREATE_LOG";
export const UPDATED_LOG = "UPDATE_LOG";
export const CREATE_LOG_SUCCEEDED = "CREATE_LOG_SUCCEEDED";
export const SEED_LOGS_BY_DATE = "SEED_LOGS_BY_DATE";

//types tour
export const TOUR_CHANGE_FIELD = "TOUR_CHANGE_FIELD";
export const CREATE_TOUR = "CREATE_TOUR";
export const CHANGE_DATE = "CHANGE_DATE";
export const GET_TOUR = "GET_TOUR";
export const SEED_TOUR = "SEED_TOUR";
export const UPDATE_TOUR = "UPDATE_TOUR";
